export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_INGREDIENT_ERROR = 'ADD_INGREDIENT_ERROR';
export const DISMISS_INGREDIENT_INFO = 'DISMISS_INGREDIENT_INFO';
export const EDIT_INGREDIENT = 'EDIT_INGREDIENT';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FETCH_INGREDIENTS_ERROR = 'FETCH_INGREDIENTS_ERROR';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const DELETE_INGREDIENT_ERROR = 'DELETE_INGREDIENT_ERROR';

