export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_INGREDIENT_ERROR = 'ADD_INGREDIENT_ERROR';
export const DISMISS_INGREDIENT_ADD = 'DISMISS_INGREDIENT_ADD';
export const EDIT_INGREDIENT = 'EDIT_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';