//Ingredient actions
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const ADD_INGREDIENT_ERROR = 'ADD_INGREDIENT_ERROR';
export const DISMISS_INGREDIENT_INFO = 'DISMISS_INGREDIENT_INFO';
export const EDIT_INGREDIENT = 'EDIT_INGREDIENT';
export const EDIT_INGREDIENT_ERROR = 'EDIT_INGREDIENT_ERROR';
export const FETCH_INGREDIENT = 'FETCH_INGREDIENT';
export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS';
export const FETCH_INGREDIENTS_ERROR = 'FETCH_INGREDIENTS_ERROR';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const DELETE_INGREDIENT_ERROR = 'DELETE_INGREDIENT_ERROR';


//Authentication actions
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_ERRORS = 'CLEAR_AUTH_ERRORS';